# Generated by Django 2.0.13 on 2019-02-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190221_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='Image',
            new_name='image',
        ),
    ]
