# Generated by Django 2.0.13 on 2019-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190225_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
